version: '3.7'

services:
  node:
    container_name: lambot_node
    build: .
    tty: true
    command: yarn build-and-start
    volumes:
      - ./config:/app/config
      - ./data/sessions:/app/data/sessions
    networks:
      - lambot-network
    ports:
      - '${SERVER_PORT_3000:-3000}:3000'

networks:
  lambot-network:
    name: labot_network
    driver: bridge
