version: '3.7'

services:
  node:
    container_name: lambot_node
    build: .
    tty: true
    command: yarn build-and-start
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - lambot-network
    ports:
      - '${SERVER_PORT_3000:-3000}:3000'

  timescale:
    container_name: lambot_timescale
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - lambot-network

networks:
  lambot-network:
    name: labot_network
    driver: bridge
